# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "REPOS" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"OWNER" VARCHAR NOT NULL,"NAME" VARCHAR NOT NULL,"ISSUESNUMBER" INTEGER NOT NULL);

# --- !Downs

drop table "REPOS";

