# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "githubRepos" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"owner" VARCHAR NOT NULL,"name" VARCHAR NOT NULL,"issuesNumber" INTEGER NOT NULL);

# --- !Downs

drop table "githubRepos";

